# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginScreen(object):
    def setupUi(self, LoginScreen):
        LoginScreen.setObjectName("LoginScreen")
        LoginScreen.resize(800, 657)
        self.centralwidget = QtWidgets.QWidget(LoginScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.Login = QtWidgets.QWidget()
        self.Login.setObjectName("Login")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Login)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.Login)
        self.frame.setMaximumSize(QtCore.QSize(400, 500))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.User = QtWidgets.QLineEdit(self.frame)
        self.User.setGeometry(QtCore.QRect(40, 130, 321, 41))
        self.User.setStyleSheet("background-color: rgb(252, 254, 255);\n"
"border-radius: 8px;\n"
"color: rgb(0, 0, 0);")
        self.User.setAlignment(QtCore.Qt.AlignCenter)
        self.User.setObjectName("User")
        self.Senha = QtWidgets.QLineEdit(self.frame)
        self.Senha.setGeometry(QtCore.QRect(40, 200, 321, 41))
        self.Senha.setStyleSheet("background-color: rgb(252, 254, 255);\n"
"border-radius: 8px;\n"
"color: rgb(0, 0, 0);")
        self.Senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Senha.setAlignment(QtCore.Qt.AlignCenter)
        self.Senha.setObjectName("Senha")
        self.btnLogar = QtWidgets.QPushButton(self.frame)
        self.btnLogar.setGeometry(QtCore.QRect(120, 280, 161, 41))
        self.btnLogar.setStyleSheet("background-color: rgb(31, 109, 153);\n"
"color: rgb(252, 254, 255);\n"
"border-radius:20px;")
        self.btnLogar.setObjectName("btnLogar")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(140, 470, 111, 18))
        self.label.setObjectName("label")
        self.btnCadastro = QtWidgets.QLabel(self.frame)
        self.btnCadastro.setGeometry(QtCore.QRect(250, 470, 41, 18))
        self.btnCadastro.setStyleSheet("color: rgb(28, 113, 216);")
        self.btnCadastro.setObjectName("btnCadastro")
        self.Aviso = QtWidgets.QFrame(self.frame)
        self.Aviso.setGeometry(QtCore.QRect(20, 10, 361, 31))
        self.Aviso.setStyleSheet("background-color: rgb(237, 51, 59);\n"
"border-radius: 15px;")
        self.Aviso.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Aviso.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Aviso.setObjectName("Aviso")
        self.avisoLabel = QtWidgets.QLabel(self.Aviso)
        self.avisoLabel.setGeometry(QtCore.QRect(10, 0, 341, 31))
        self.avisoLabel.setStyleSheet("color: rgb(252, 254, 255);")
        self.avisoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.avisoLabel.setObjectName("avisoLabel")
        self.btnFecharAviso = QtWidgets.QPushButton(self.Aviso)
        self.btnFecharAviso.setGeometry(QtCore.QRect(320, 0, 41, 31))
        self.btnFecharAviso.setStyleSheet("background-color: rgb(62, 63, 64);\n"
"color: rgb(252, 254, 255);")
        self.btnFecharAviso.setObjectName("btnFecharAviso")
        self.horizontalLayout_2.addWidget(self.frame)
        self.stackedWidget.addWidget(self.Login)
        self.Cadastrar = QtWidgets.QWidget()
        self.Cadastrar.setObjectName("Cadastrar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Cadastrar)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.Cadastrar)
        self.frame_2.setMaximumSize(QtCore.QSize(724, 624))
        self.frame_2.setStyleSheet("border: none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.Hospital = QtWidgets.QLineEdit(self.frame_2)
        self.Hospital.setGeometry(QtCore.QRect(120, 20, 491, 41))
        self.Hospital.setStyleSheet("background-color: rgb(252, 254, 255);\n"
"border-radius: 8px;\n"
"color: rgb(0, 0, 0);")
        self.Hospital.setText("")
        self.Hospital.setAlignment(QtCore.Qt.AlignCenter)
        self.Hospital.setObjectName("Hospital")
        self.UserC = QtWidgets.QLineEdit(self.frame_2)
        self.UserC.setGeometry(QtCore.QRect(120, 80, 491, 41))
        self.UserC.setStyleSheet("background-color: rgb(252, 254, 255);\n"
"border-radius: 8px;\n"
"color: rgb(0, 0, 0);")
        self.UserC.setText("")
        self.UserC.setAlignment(QtCore.Qt.AlignCenter)
        self.UserC.setObjectName("UserC")
        self.Email = QtWidgets.QLineEdit(self.frame_2)
        self.Email.setGeometry(QtCore.QRect(120, 140, 491, 41))
        self.Email.setStyleSheet("background-color: rgb(252, 254, 255);\n"
"border-radius: 8px;\n"
"color: rgb(0, 0, 0);")
        self.Email.setText("")
        self.Email.setAlignment(QtCore.Qt.AlignCenter)
        self.Email.setObjectName("Email")
        self.SenhaC = QtWidgets.QLineEdit(self.frame_2)
        self.SenhaC.setGeometry(QtCore.QRect(120, 210, 241, 41))
        self.SenhaC.setStyleSheet("background-color: rgb(252, 254, 255);\n"
"border-radius: 8px;\n"
"color: rgb(0, 0, 0);")
        self.SenhaC.setText("")
        self.SenhaC.setAlignment(QtCore.Qt.AlignCenter)
        self.SenhaC.setObjectName("SenhaC")
        self.RepetirSenha = QtWidgets.QLineEdit(self.frame_2)
        self.RepetirSenha.setGeometry(QtCore.QRect(380, 210, 231, 41))
        self.RepetirSenha.setStyleSheet("background-color: rgb(252, 254, 255);\n"
"border-radius: 8px;\n"
"color: rgb(0, 0, 0);")
        self.RepetirSenha.setText("")
        self.RepetirSenha.setAlignment(QtCore.Qt.AlignCenter)
        self.RepetirSenha.setObjectName("RepetirSenha")
        self.Rua = QtWidgets.QLineEdit(self.frame_2)
        self.Rua.setGeometry(QtCore.QRect(120, 280, 241, 41))
        self.Rua.setStyleSheet("background-color: rgb(252, 254, 255);\n"
"border-radius: 8px;\n"
"color: rgb(0, 0, 0);")
        self.Rua.setText("")
        self.Rua.setAlignment(QtCore.Qt.AlignCenter)
        self.Rua.setObjectName("Rua")
        self.Numero = QtWidgets.QLineEdit(self.frame_2)
        self.Numero.setGeometry(QtCore.QRect(380, 280, 231, 41))
        self.Numero.setStyleSheet("background-color: rgb(252, 254, 255);\n"
"border-radius: 8px;\n"
"color: rgb(0, 0, 0);")
        self.Numero.setText("")
        self.Numero.setAlignment(QtCore.Qt.AlignCenter)
        self.Numero.setObjectName("Numero")
        self.Cidade = QtWidgets.QLineEdit(self.frame_2)
        self.Cidade.setGeometry(QtCore.QRect(120, 340, 241, 41))
        self.Cidade.setStyleSheet("background-color: rgb(252, 254, 255);\n"
"border-radius: 8px;\n"
"color: rgb(0, 0, 0);")
        self.Cidade.setText("")
        self.Cidade.setAlignment(QtCore.Qt.AlignCenter)
        self.Cidade.setObjectName("Cidade")
        self.Bairro = QtWidgets.QLineEdit(self.frame_2)
        self.Bairro.setGeometry(QtCore.QRect(380, 340, 231, 41))
        self.Bairro.setStyleSheet("background-color: rgb(252, 254, 255);\n"
"border-radius: 8px;\n"
"color: rgb(0, 0, 0);")
        self.Bairro.setText("")
        self.Bairro.setAlignment(QtCore.Qt.AlignCenter)
        self.Bairro.setObjectName("Bairro")
        self.Cep = QtWidgets.QLineEdit(self.frame_2)
        self.Cep.setGeometry(QtCore.QRect(120, 400, 241, 41))
        self.Cep.setStyleSheet("background-color: rgb(252, 254, 255);\n"
"border-radius: 8px;\n"
"color: rgb(0, 0, 0);")
        self.Cep.setText("")
        self.Cep.setAlignment(QtCore.Qt.AlignCenter)
        self.Cep.setObjectName("Cep")
        self.Estado = QtWidgets.QLineEdit(self.frame_2)
        self.Estado.setGeometry(QtCore.QRect(380, 400, 231, 41))
        self.Estado.setStyleSheet("background-color: rgb(252, 254, 255);\n"
"border-radius: 8px;\n"
"color: rgb(0, 0, 0);")
        self.Estado.setText("")
        self.Estado.setAlignment(QtCore.Qt.AlignCenter)
        self.Estado.setObjectName("Estado")
        self.Telefone = QtWidgets.QLineEdit(self.frame_2)
        self.Telefone.setGeometry(QtCore.QRect(120, 460, 241, 41))
        self.Telefone.setStyleSheet("background-color: rgb(252, 254, 255);\n"
"border-radius: 8px;\n"
"color: rgb(0, 0, 0);")
        self.Telefone.setText("")
        self.Telefone.setAlignment(QtCore.Qt.AlignCenter)
        self.Telefone.setObjectName("Telefone")
        self.radioPublico = QtWidgets.QRadioButton(self.frame_2)
        self.radioPublico.setGeometry(QtCore.QRect(250, 520, 102, 24))
        self.radioPublico.setObjectName("radioPublico")
        self.radioPrivado = QtWidgets.QRadioButton(self.frame_2)
        self.radioPrivado.setGeometry(QtCore.QRect(400, 520, 102, 24))
        self.radioPrivado.setChecked(True)
        self.radioPrivado.setObjectName("radioPrivado")
        self.btnCadastrar = QtWidgets.QPushButton(self.frame_2)
        self.btnCadastrar.setGeometry(QtCore.QRect(380, 570, 221, 41))
        self.btnCadastrar.setStyleSheet("background-color: rgb(31, 109, 153);\n"
"color: rgb(252, 254, 255);\n"
"border-radius:20px;")
        self.btnCadastrar.setObjectName("btnCadastrar")
        self.btnVoltar = QtWidgets.QPushButton(self.frame_2)
        self.btnVoltar.setGeometry(QtCore.QRect(120, 570, 221, 41))
        self.btnVoltar.setStyleSheet("background-color: rgb(82, 160, 204);\n"
"color: rgb(252, 254, 255);\n"
"border-radius:20px;")
        self.btnVoltar.setObjectName("btnVoltar")
        self.Cnes = QtWidgets.QLineEdit(self.frame_2)
        self.Cnes.setGeometry(QtCore.QRect(380, 460, 231, 41))
        self.Cnes.setStyleSheet("background-color: rgb(252, 254, 255);\n"
"border-radius: 8px;\n"
"color: rgb(0, 0, 0);")
        self.Cnes.setText("")
        self.Cnes.setAlignment(QtCore.Qt.AlignCenter)
        self.Cnes.setObjectName("Cnes")
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.stackedWidget.addWidget(self.Cadastrar)
        self.horizontalLayout.addWidget(self.stackedWidget)
        LoginScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginScreen)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LoginScreen)

    def retranslateUi(self, LoginScreen):
        _translate = QtCore.QCoreApplication.translate
        LoginScreen.setWindowTitle(_translate("LoginScreen", "MainWindow"))
        self.User.setPlaceholderText(_translate("LoginScreen", "USER"))
        self.Senha.setPlaceholderText(_translate("LoginScreen", "SENHA"))
        self.btnLogar.setText(_translate("LoginScreen", "Logar"))
        self.label.setText(_translate("LoginScreen", "Solicitar cadastro"))
        self.btnCadastro.setText(_translate("LoginScreen", "Aqui"))
        self.avisoLabel.setText(_translate("LoginScreen", "Error"))
        self.btnFecharAviso.setText(_translate("LoginScreen", "X"))
        self.Hospital.setPlaceholderText(_translate("LoginScreen", "HOSPITAL"))
        self.UserC.setPlaceholderText(_translate("LoginScreen", "USUARIO"))
        self.Email.setPlaceholderText(_translate("LoginScreen", "E-MAIL"))
        self.SenhaC.setPlaceholderText(_translate("LoginScreen", "SENHA"))
        self.RepetirSenha.setPlaceholderText(_translate("LoginScreen", "REPETIR SENHA"))
        self.Rua.setPlaceholderText(_translate("LoginScreen", "RUA"))
        self.Numero.setPlaceholderText(_translate("LoginScreen", "N°"))
        self.Cidade.setPlaceholderText(_translate("LoginScreen", "CIDADE"))
        self.Bairro.setPlaceholderText(_translate("LoginScreen", "BAIRRO"))
        self.Cep.setPlaceholderText(_translate("LoginScreen", "CEP"))
        self.Estado.setPlaceholderText(_translate("LoginScreen", "ESTADO"))
        self.Telefone.setPlaceholderText(_translate("LoginScreen", "TELEFONE"))
        self.radioPublico.setText(_translate("LoginScreen", "PUBLICO"))
        self.radioPrivado.setText(_translate("LoginScreen", "PRIVADO"))
        self.btnCadastrar.setText(_translate("LoginScreen", "Cadastrar"))
        self.btnVoltar.setText(_translate("LoginScreen", "Voltar"))
        self.Cnes.setPlaceholderText(_translate("LoginScreen", "CNES"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginScreen = QtWidgets.QMainWindow()
    ui = Ui_LoginScreen()
    ui.setupUi(LoginScreen)
    LoginScreen.show()
    sys.exit(app.exec_())
